<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV4yxnjd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV4yxnjd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerV4yxnjd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerV4yxnjd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerV4yxnjd\appDevDebugProjectContainer();
